name: Code Coverage

on:
  push:
    branches:
      - master # Replace with your branch name

jobs:
  coverage:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x # Replace with your Python version

      - name: Install dependencies
        run: |
          pip install -r dev-requirements.txt
          pip install coverage

      - name: Run tests with coverage and generate HTML report
        run: |
          coverage run manage.py test
          coverage report
          coverage html

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./htmlcov # Adjust this directory if coverage reports are in a different location
          token: ${{ secrets.CODECOV_TOKEN }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
